name: update changelog and generate release notes

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: install auto-changelog
        run: npm install auto-changelog

      - name: generate changelog
        run: >-
          npx auto-changelog -t keepachangelog
          --commit-limit 50 --backfill-limit 50
          --ignore-commit-pattern '[Bb]ump version|[Uu]pdate changelog|[Mm]erge pull request'

      - name: get release notes
        id: release-notes
        uses: olofvndrhr/releasenote-gen@v1

      - name: create github release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          body: ${{ steps.release-notes.outputs.releasenotes }}

      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: CHANGELOG.md
          message: "[bot] update changelog"
          default_author: github_actions
